#pragma once

// GXM Constants from Vita3K
#define SCE_GXM_DEFAULT_UNIFORM_BUFFER_CONTAINER_INDEX 0
#define SCE_GXM_GPU_CORE_COUNT 4U
#define SCE_GXM_MAX_VERTEX_STREAMS 16
#define SCE_GXM_MAX_TEXTURE_UNITS 16
#define SCE_GXM_MAX_UNIFORM_BUFFERS 14
#define SCE_GXM_UNIFORM_BUFFER_OFFSET 1
#define SCE_GXM_REAL_MAX_UNIFORM_BUFFER (SCE_GXM_MAX_UNIFORM_BUFFERS + 1) // Include default
#define SCE_GXM_DEFAULT_UNIFORM_BUFFER 14
#define SCE_GXM_TEXTURE_BUFFER 15
#define SCE_GXM_LITERAL_BUFFER 16
#define SCE_GXM_THREAD_BUFFER 18
#define SCE_GXM_COLOR_BASE_FORMAT_MASK 0xF1800000U
#define SCE_GXM_COLOR_SWIZZLE_MASK 0x00300000U
#define SCE_GXM_TEXTURE_BASE_FORMAT_MASK 0x9F000000U
#define SCE_GXM_TEXTURE_SWIZZLE_MASK 0x00007000U
#define SCE_GXM_TILE_SHIFTX 5U
#define SCE_GXM_TILE_SHIFTY 5U
#define SCE_GXM_TILE_SIZEX (1U << SCE_GXM_TILE_SHIFTX)
#define SCE_GXM_TILE_SIZEY (1U << SCE_GXM_TILE_SHIFTY)
#define SCE_GXM_VISIBILITY_ALIGNMENT 16U
